django/image/delivered_files/portfolioSite/server/portfolio/urls.py
from django.conf.urls import url
from django.urls import path
from portfolio import views

# Template tagging
app_name = 'portfolio'

urlpatterns = [
    path('', views.portfolioHome, name='portfolioHome'),
]

django/image/delivered_files/portfolioSite/server/server/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from server.views import index

urlpatterns = [
    path('', index, name='index'),
    path('portfolio/',include('portfolio.urls')),
    path('admin/', admin.site.urls),
]

django/image/delivered_files/portfolioSite/server/portfolio/models.py
from django.db import models

# Create your models here.

django/image/delivered_files/portfolioSite/server/portfolio/views.py
from django.shortcuts import render

# Create your views here.
def portfolioHome(request):
    return render(request,'portfolio/portfolioHome.html',{})

django/image/delivered_files/portfolioSite/server/server/views.py
from django.shortcuts import render

def index(request):
    return render(request,'server/index.html',{})

django/image/delivered_files/portfolioSite/server/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>TheProject</title>
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggler">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <!-- <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:portfolioHome' %}">My Portfolio</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
      {% block body_block %}
      <!-- Extending the base.html -->
      {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

django/image/delivered_files/portfolioSite/server/templates/portfolio/portfolioBase.html
{% extends "base/base.html" %}
  {% block body_block %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'portfolio:portfolioHome' %}">Portfolio</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'portfolio:portfolioHome' %}">My Portfolio</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block portfolio_block %}
    <!-- Extending the base.html -->
    {% endblock %}
  </div>
  {% endblock %}

django/image/delivered_files/portfolioSite/server/templates/portfolio/portfolioHome.html
{% extends "portfolio/portfolioBase.html" %}
  {% block portfolio_block %}
    <div class="jumbotron">
      <h2>Welcome to My Portfolio</h2>
    </div>
  {% endblock %}

django/image/delivered_files/portfolioSite/server/templates/server/index.html
{% extends "base/base.html" %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h2>Welcome to The Project</h2>
    </div>
  </div>
  {% endblock %}